---
- name: Backups ansible
  hosts: all
  tasks:
   - name: Crear respaldo /home/ansible de cada Equipo 
     shell: /bin/tar -cvf /tmp/respaldo{{ ansible_hostname }}.tar /home/ansible
    
   - name: Copy Remote-To-hosts
     hosts: 10.0.2.15
     synchronize: dest=/home/ansible/backups/ src=/tmp/respaldo*tar
     delegate_to: 10.0.2.19
   - name: Remove old files foo
     file: path=/tmp/respaldo*.tar state=absent
    
