---
- name: Buscar archivos
  hosts: all
  tasks:
    - name: Buscar archivos en  /tmp creados hace mas de 2 days
      find:
       paths: /tmp
       age: 2d
       recurse: yes
       register: contents 
    - name: Muestro1
       debug: var=contents.stdout_lines
