---
- name: This sets up an httpd webserver
  hosts: 10.0.2.19
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    command: systemctl restart httpd.service
    register: timestamp_end
  - debug: var=timestamp_end

  - name: verify that the web service is running
    command: systemctl status httpd.service
    register: result
  - debug: var=result
