---
- hosts: all
  
  tasks:
  - name: Recopilar IPs
    shell: /sbin/ifconfig | grep inet.*cast
    
- hosts: fedora
 
  tasks:
  - name: Install Vim
    yum: name=vim state=installed update_cache=true
    
 
