---
- name: This sets up an httpd webserver
  hosts: Ubuntu
  tasks:
  - name: Install apache packages 
    apt:
      name: apache2
      state: present
  - name: ensure apache is running
    command: systemctl restart apache2.service
    register: timestamp_end
  - debug: var=timestamp_end

  - name: verify that the web service is running
    command: systemctl status apache2.service
    register: result
  - debug: var=result

