---
- hosts: all
  
  tasks:
  - name: Recopilar IPs
    shell: /sbin/ifconfig | grep inet.*cast
    register: contents 
  - name: Muestro1
    debug: var=contents.stdout_lines
    
- hosts: Fedora
 
  tasks:
  - name: Install Vim
    yum: name=vim state=installed update_cache=true
    
 
